#!/usr/bin/env node
// Regenerates the index at the top of AGENT_LOG.md from the entries themselves, so it can't drift.
// Only the block between the index markers is rewritten; entries are never touched.
// Usage: node .claude/skills/agent-log/scripts/index.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const log = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../AGENT_LOG.md');
const START = '<!-- index:start (generated by .claude/skills/agent-log/scripts/index.mjs) -->';
const END = '<!-- index:end -->';
const text = readFileSync(log, 'utf8');

/** First sentence of a field, trimmed to a table cell: pipes escaped, markdown kept. */
const cell = (s, max = 140) => {
  const first = s.replace(/\s+/g, ' ').trim().replace(/^- /, '').split(/(?<=\.)\s/)[0] ?? '';
  const short = first.length > max ? `${first.slice(0, max - 1).trimEnd()}…` : first;
  return short.replaceAll('|', '\\|');
};

const entries = [...text.matchAll(/^## Entry (\d+): (.+)$/gm)].map((m, i, all) => {
  const body = text.slice(m.index, all[i + 1]?.index ?? text.length);
  const field = (name) => body.match(new RegExp(`\\*\\*${name}:\\*\\*([\\s\\S]*?)(?=\\n- \\*\\*|\\n## |$)`))?.[1] ?? '';
  const rejected = field('Rejected / corrected').trim().split('\n').find((l) => l.trim()) ?? '';
  return `| ${m[1]} | ${field('When').trim().slice(5, 16)} | ${cell(m[2], 70)} | ${cell(rejected)} |`;
});

const index = [
  START,
  '',
  `## Index (${entries.length} entries)`,
  '',
  'One row per entry, with the first thing rejected or corrected. The full entries follow, in order.',
  '',
  '| # | When | Entry | First thing rejected or corrected |',
  '|---|---|---|---|',
  ...entries,
  '',
  END,
].join('\n');

const hasIndex = text.includes(START) && text.includes(END);
const next = hasIndex
  ? text.slice(0, text.indexOf(START)) + index + text.slice(text.indexOf(END) + END.length)
  : text.replace(/^(# Agent Log\n\n[^\n]*\n)/, `$1\n${index}\n`);
if (next === text && !hasIndex) throw new Error('AGENT_LOG.md header not found; index not written');
writeFileSync(log, next);
console.log(`Index: ${entries.length} entries`);
